name: DATN
recipe: laravel
config:
  webroot: public
  php: '8.2'
  database: DATN-DB

services:
  appserver:
    type: php:8.2
    build_as_root:
      - apt-get update -y
      - apt-get install -y zip unzip
    overrides:
      ports:
        - 8081:80  # Đặt cổng 8081 cho dự án này

  database:
    type: mysql:8.0
    portforward: 3309  # Đặt cổng 3309 cho MySQL
    creds:
      user: laravel
      password: laravel
      database: DATN-DB

tooling:
  composer:
    service: appserver
  artisan:
    service: appserver

env:
  - DB_CONNECTION=mysql
  - DB_HOST=database
  - DB_PORT=3306
  - DB_DATABASE=DATN-DB
  - DB_USERNAME=laravel
  - DB_PASSWORD=laravel